[project]
name = "ai-form-builder"
version = "0.1.0"
description = "A FastAPI backend for an AI form building application"
authors = [{ name = "Franklin Ikeh", email = "ikehfranklin06@gmail.com" }]
requires-python = ">=3.12,<4"
readme = "README.md"

dependencies = [
    "alembic>=1.14.0,<2",
    "bcrypt>=5.0.0",
    "cryptography>=43.0.3,<47",
    "fastapi[standard]>=0.115.6,<0.116",
    "google-api-python-client>=2.159.0,<3",
    "google-auth-httplib2>=0.2.0,<1",
    "google-auth-oauthlib>=1.2.1,<2",
    "google-auth[requests]>=2.40,<3",
    "groq>=1.4.0",
    "itsdangerous>=2.2.0,<3",
    "psycopg2-binary>=2.9.10,<3",
    "pydantic-settings>=2.7.0,<3",
    "python-jose>=3.3.0,<4",
    "slowapi>=0.1.0,<0.2",
    "uuid7>=0.1.0,<0.2",
    "uvicorn>=0.34.0,<0.35",
]

[dependency-groups]
dev = [
    "ruff>=0.8.3,<0.9",
    "pytest>=8.3.4,<9",
]

[tool.uv]
default-groups = "all"
