"""add user_google_tokens

Revision ID: b32cbbde39b9
Revises: 5435e0360c77
Create Date: 2026-09-11 21:29:00.925961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b32cbbde39b9'
down_revision: Union[str, None] = '5435e0360c77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_google_tokens',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('google_refresh_token', sa.Text(), nullable=False),
    sa.Column('google_email', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_google_tokens_id'), 'user_google_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_user_google_tokens_user_id'), 'user_google_tokens', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_google_tokens_user_id'), table_name='user_google_tokens')
    op.drop_index(op.f('ix_user_google_tokens_id'), table_name='user_google_tokens')
    op.drop_table('user_google_tokens')
    # ### end Alembic commands ###
